/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Black: typeof import('./components/Black.vue')['default']
    LayoutDefault: typeof import('./components/LayoutDefault.vue')['default']
    LayoutTabbar: typeof import('./components/LayoutTabbar.vue')['default']
    LayoutTabbar2: typeof import('./components/LayoutTabbar2.vue')['default']
    LayoutTabbarLoading: typeof import('./components/LayoutTabbarLoading.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./components/TabBar.vue')['default']
    UnlockRecordItem: typeof import('./components/UnlockRecordItem.vue')['default']
  }
}
